CXX = g++
CXXFLAGS = -std=c++11 -Wall
TARGET = myprogram

SRCS = main.cpp savingToFile.cpp Account/User.cpp Account/Account.cpp Motorbike.cpp Request.cpp Rating.cpp TimeSlot.cpp City.cpp Account/Admin.cpp
OBJS = $(SRCS:.cpp=.o)

$(TARGET): $(OBJS)
    $(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
    $(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
    rm -f $(OBJS) $(TARGET)
